Carrera-Dev-Consulting/zombie_nomnom

- .github/workflows/deploy-docs.yaml
- makefile
- tests/unit/zombie_dice/models/test_bag.py
- zombie_dice/models/bag.py
Adding coverage html to docs so that we can have even more stuff in our github pages.
> Build docs with coverage info

- pyproject.toml
- zombie_dice/__main__.py
- zombie_dice/app.py
- zombie_dice/cli.py
Making library executable after it is installed via pip install . i.e. when it is downloaded as a package.
> Making app executable after installation

- README.md
Adding more clarity in the read me about contributing to the repo.
#18 Creating contribution guide
> Fixing contribution header

- .github/ISSUE_TEMPLATE/security-issue.md
- CODEOWNERS
- tests/integration/zombie_nomnom/test_cli.py
- tests/unit/zombie_nomnom/models/test_bag.py
- tests/unit/zombie_nomnom/test_engine.py
- zombie_nomnom/__init__.py
- zombie_nomnom/cli.py
- zombie_nomnom/engine.py
- zombie_nomnom/models/bag.py
Adding new commands to be able to `DrawDice` and `Score` to be able to use with our engine.
#14
> Create Commands for the engine to play the game

- tests/integration/zombie_nomnom/test_engine.py
- tests/unit/zombie_nomnom/test_engine.py
- zombie_nomnom/engine.py
Fixing the engine to work correctly now that we have actions to play the game and make sure we can get to an endgame that we configure via the score_threshold fields.
#28
> 28 feat create endgame in engine

- .github/workflows/deploy-docs.yaml
Adding code coverage pushes to main.
Closes #32
> Adding code coverage saving on main again.

- .github/labeler.yml
- .github/workflows/deploy-docs.yaml
- .github/workflows/label.yml
- .github/workflows/python-publish.yml
- .github/workflows/test-coverage.yml
Adding pr auto-labeler for adding tags automagically to PRs when they are changed.
Closes #22
> Adding Labeler github action.

- .github/workflows/label.yml
> Trying to fix the labeler

- makefile
- tests/integration/zombie_nomnom/conftest.py
- tests/integration/zombie_nomnom/test_cli.py
- tests/integration/zombie_nomnom/test_engine.py
- tests/unit/zombie_nomnom/test_cli.py
- tests/unit/zombie_nomnom/test_engine.py
- zombie_nomnom/cli.py
- zombie_nomnom/engine.py
Adding cli commands to make game playable.
#15
> Adding cli actions to be able to play zombie-nomnom!!

- .github/workflows/bandit.yml
- .github/workflows/scanner.yml
Adding Bandit Scanning to Source Code.
Closes #17
> Adding Python Security Scanner

- .github/workflows/pr-validator.yml
> chore(#38): Adding PR Title Checker 

- README.md
- makefile
- zombie_nomnom/__init__.py
- zombie_nomnom/app.py
- zombie_nomnom/cli.py
- zombie_nomnom/engine.py
- zombie_nomnom/models/bag.py
- zombie_nomnom/models/dice.py
Adding docstring updates to the code for the engine we are using.
Closes #16
> docs(#16): Adding Docs to the code.

- .github/workflows/deploy-docs.yaml
Adding some stuff to make release notes, and releases automagically for us.
Closes #42
> chore(changelog): Adding Release steps to automate releases and create a CHANGELOG.md

- .github/workflows/deploy-docs.yaml
Giving the action that opens the pr the ability to do that.
N/A
> chore(changelog): Giving releases actions enough permissions to open pr.

- .github/workflows/deploy-docs.yaml
Updating the version of the changelog action to get rid of warnings.
N/A
> chore(changelog): Update changelog action version.

- .github/workflows/deploy-docs.yaml
Updating action config to skip any release that already exist i.e. when we rerun the workflow again on main.
N/A
> chore(releases): Adding param to skip releases so we can rerun the workflow on failures.

- .github/workflows/deploy-docs.yaml
- .github/workflows/python-publish.yml
Only makes changelog updates after a release instead of on merges.
N/A
> chore(changelog): Changing how and when we create change log changes.

- .github/workflows/scanner.yml
Using an updated bandit code scanner action.
Closes #51
> chore(security): Update github action for bandit to use more updated version.

- pyproject.toml
Use regex to find actual valid version in tags
> chore(versioning): Fixing version to lookup valid versions.

- tests/unit/zombie_nomnom/models/test_dice.py
- zombie_nomnom/models/dice.py
made a test case that checks if a dice returns a color.
> feat: adding name field

- .github/workflows/python-publish.yml
Setting the PDM_VERSION variable to the tag that was given.
> build(pypi): Fix the issue to deploy to pypi by hard setting version.

- tests/unit/zombie_nomnom/models/test_dice.py
- tests/unit/zombie_nomnom/test_engine.py
- zombie_nomnom/engine.py
- zombie_nomnom/models/dice.py
wrote the dieface code to allow for custom dice that produce extra damage or points. 
closes #26
> feat: custom faces edits
